
import Model.Clothes;
import Model.Regex;
import java.awt.Image;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Optional;
import javax.accessibility.AccessibleRole;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Nghia
 */
public class JFrame extends javax.swing.JFrame {
    private List<Clothes> list = new ArrayList<>();
    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();
        NumberFormat nf = NumberFormat.getInstance(new Locale("en", "US"));
        JLabel num = enterNum;
        JLabel num1 = enterNum1;
        num.setVisible(false);
        num1.setVisible(false);
        DefaultTableModel dtm = (DefaultTableModel) displayTable.getModel();
        
        JLabel logo1 = logoLabel;
        logo1.setBounds(0, 0, 400, 300);
        String path = "C:\\Users\\Nghia\\Downloads\\LV.jpg";
        ImageIcon myImage = new ImageIcon(path);
        Image img = myImage.getImage();
        Image newImg = img.getScaledInstance(logo1.getWidth(), logo1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        logo1.setIcon(image);
        
        JLabel logo2 = logo2Label;
        logo2.setBounds(0, 0, 700, 776);
        String path2 = "C:\\Users\\Nghia\\Downloads\\LV2.jpg";
        ImageIcon myImage2 = new ImageIcon(path2);
        Image img2 = myImage2.getImage();
        Image newImg2 = img2.getScaledInstance(logo2.getWidth(), logo2.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image2 = new ImageIcon(newImg2);
        logo2.setIcon(image2);
        
//        list.add(new Clothes("Jacket", "M", 80, 3200000));
//        list.add(new Clothes("Hoodie", "L", 100, 280000));
//        list.add(new Clothes("Longtee", "S", 120, 180000));
//        list.add(new Clothes("Long Sleeves", "L", 90, 150000));
//        list.add(new Clothes("Jacket Bomber", "L", 120, 320000));
        FileInputStream file = null;
        ObjectInputStream obj = null;
        try{
            file = new FileInputStream("clothes.dat");
            obj = new ObjectInputStream(file);
            
            list = (List<Clothes>) obj.readObject();
            file.close();
            obj.close();
        }catch(Exception ex){
            ex.getStackTrace();
        }

        
        for(int i=0; i<list.size(); i++){
            dtm.addRow(new Object[]{list.get(i).getId(), list.get(i).getName(), list.get(i).getSize(), list.get(i).getAmount(), nf.format(list.get(i).getPrice())});
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SellDialog = new javax.swing.JDialog();
        sellAmountLabel = new javax.swing.JLabel();
        SellAmountTextField = new javax.swing.JTextField();
        SellAmountButton = new javax.swing.JButton();
        findDialog = new javax.swing.JDialog();
        findByName = new javax.swing.JLabel();
        findByNameText = new javax.swing.JTextField();
        findByNameButton = new javax.swing.JButton();
        findBySize = new javax.swing.JLabel();
        findBySizeTextField = new javax.swing.JTextField();
        findBySizeButton = new javax.swing.JButton();
        findByPrice = new javax.swing.JLabel();
        findMinText = new javax.swing.JTextField();
        findByPrice1 = new javax.swing.JLabel();
        findMaxText = new javax.swing.JTextField();
        findByPrice2 = new javax.swing.JLabel();
        findByPriceButton = new javax.swing.JButton();
        editDialog = new javax.swing.JDialog();
        editSizeSelect = new javax.swing.JComboBox<>();
        sizeLabel2 = new javax.swing.JLabel();
        amountLabel1 = new javax.swing.JLabel();
        editAmountText = new javax.swing.JTextField();
        editPriceText = new javax.swing.JTextField();
        priceLabel1 = new javax.swing.JLabel();
        nameLabel1 = new javax.swing.JLabel();
        editNameText = new javax.swing.JTextField();
        okEditButton = new javax.swing.JButton();
        deleteDialog = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        No = new javax.swing.JButton();
        Yes = new javax.swing.JButton();
        Student = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        priceTextField = new javax.swing.JTextField();
        amountLabel = new javax.swing.JLabel();
        amountTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        sizeLabel1 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        sellButton = new javax.swing.JButton();
        FindButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        viewAllButton = new javax.swing.JButton();
        sizeSelect = new javax.swing.JComboBox<>();
        enterNum = new javax.swing.JLabel();
        enterNum1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTable = new javax.swing.JTable();
        logoLabel = new javax.swing.JLabel();
        logo2Label = new javax.swing.JLabel();

        sellAmountLabel.setText("Enter Amount:");

        SellAmountTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SellAmountTextFieldActionPerformed(evt);
            }
        });

        SellAmountButton.setText("OK");
        SellAmountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SellAmountButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SellDialogLayout = new javax.swing.GroupLayout(SellDialog.getContentPane());
        SellDialog.getContentPane().setLayout(SellDialogLayout);
        SellDialogLayout.setHorizontalGroup(
            SellDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SellDialogLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(sellAmountLabel)
                .addGap(18, 18, 18)
                .addComponent(SellAmountTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SellAmountButton)
                .addContainerGap())
        );
        SellDialogLayout.setVerticalGroup(
            SellDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SellDialogLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(SellDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sellAmountLabel)
                    .addComponent(SellAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SellAmountButton))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        findByName.setText("Find By Name:");

        findByNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findByNameTextActionPerformed(evt);
            }
        });

        findByNameButton.setText("OK");
        findByNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findByNameButtonActionPerformed(evt);
            }
        });

        findBySize.setText("Find By Size:");

        findBySizeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findBySizeTextFieldActionPerformed(evt);
            }
        });

        findBySizeButton.setText("OK");
        findBySizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findBySizeButtonActionPerformed(evt);
            }
        });

        findByPrice.setText("Find By Price:");

        findMinText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findMinTextActionPerformed(evt);
            }
        });

        findByPrice1.setText(",000   -");

        findMaxText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findMaxTextActionPerformed(evt);
            }
        });

        findByPrice2.setText(",000");

        findByPriceButton.setText("OK");
        findByPriceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findByPriceButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout findDialogLayout = new javax.swing.GroupLayout(findDialog.getContentPane());
        findDialog.getContentPane().setLayout(findDialogLayout);
        findDialogLayout.setHorizontalGroup(
            findDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(findDialogLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(findDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(findDialogLayout.createSequentialGroup()
                        .addGroup(findDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(findByPrice)
                            .addComponent(findBySize))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(findBySizeButton))
                    .addGroup(findDialogLayout.createSequentialGroup()
                        .addGroup(findDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(findDialogLayout.createSequentialGroup()
                                .addComponent(findByName)
                                .addGap(18, 18, 18)
                                .addComponent(findByNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(findDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(findDialogLayout.createSequentialGroup()
                                    .addComponent(findMinText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(findByPrice1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(findMaxText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(findByPrice2))
                                .addComponent(findBySizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(findDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(findByNameButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(findByPriceButton, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(28, 28, 28))
        );
        findDialogLayout.setVerticalGroup(
            findDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(findDialogLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(findDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findByName)
                    .addComponent(findByNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findByNameButton))
                .addGap(34, 34, 34)
                .addGroup(findDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findBySize)
                    .addComponent(findBySizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findBySizeButton))
                .addGap(38, 38, 38)
                .addGroup(findDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findByPrice)
                    .addComponent(findMinText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findByPrice1)
                    .addComponent(findMaxText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findByPrice2)
                    .addComponent(findByPriceButton))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        editSizeSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S", "M", "L" }));
        editSizeSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSizeSelectActionPerformed(evt);
            }
        });

        sizeLabel2.setText("Size: ");

        amountLabel1.setText("Amount: ");

        editAmountText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAmountTextActionPerformed(evt);
            }
        });

        editPriceText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPriceTextActionPerformed(evt);
            }
        });
        editPriceText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                editPriceTextKeyPressed(evt);
            }
        });

        priceLabel1.setText("Price:");

        nameLabel1.setText("Name: ");

        editNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editNameTextActionPerformed(evt);
            }
        });

        okEditButton.setText("OK");
        okEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okEditButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editDialogLayout = new javax.swing.GroupLayout(editDialog.getContentPane());
        editDialog.getContentPane().setLayout(editDialogLayout);
        editDialogLayout.setHorizontalGroup(
            editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editDialogLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel1)
                    .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(amountLabel1)
                        .addComponent(priceLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(sizeLabel2))
                .addGap(18, 18, 18)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editDialogLayout.createSequentialGroup()
                        .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(editNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(editPriceText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                                .addComponent(editAmountText, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addContainerGap(61, Short.MAX_VALUE))
                    .addGroup(editDialogLayout.createSequentialGroup()
                        .addComponent(editSizeSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(okEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129))))
        );
        editDialogLayout.setVerticalGroup(
            editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editDialogLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel1)
                    .addComponent(editNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLabel1)
                    .addComponent(editPriceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountLabel1)
                    .addComponent(editAmountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editDialogLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(sizeLabel2))
                    .addGroup(editDialogLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editSizeSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(okEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        editDialog.getAccessibleContext().setAccessibleName("Input Edit Infomation");

        jLabel1.setText("Do You Want To Delete This Item?");

        No.setText("No");
        No.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoActionPerformed(evt);
            }
        });

        Yes.setText("Yes");
        Yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deleteDialogLayout = new javax.swing.GroupLayout(deleteDialog.getContentPane());
        deleteDialog.getContentPane().setLayout(deleteDialogLayout);
        deleteDialogLayout.setHorizontalGroup(
            deleteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteDialogLayout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addGroup(deleteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(deleteDialogLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(Yes)
                        .addGap(42, 42, 42)
                        .addComponent(No, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(80, 80, 80))
        );
        deleteDialogLayout.setVerticalGroup(
            deleteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteDialogLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(deleteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(No)
                    .addComponent(Yes))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Student.setBorder(javax.swing.BorderFactory.createTitledBorder("Input Food's Detail Information"));

        nameLabel.setText("Name: ");

        priceLabel.setText("Price:");

        priceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTextFieldActionPerformed(evt);
            }
        });
        priceTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                priceTextFieldKeyPressed(evt);
            }
        });

        amountLabel.setText("Amount: ");

        amountTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountTextFieldActionPerformed(evt);
            }
        });
        amountTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                amountTextFieldKeyPressed(evt);
            }
        });

        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        sizeLabel1.setText("Size: ");

        addButton.setText("Add");
        addButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addButtonMouseClicked(evt);
            }
        });
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        sellButton.setText("Sold Item");
        sellButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellButtonActionPerformed(evt);
            }
        });

        FindButton.setText("Find");
        FindButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                FindButtonMouseDragged(evt);
            }
        });
        FindButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        viewAllButton.setText("View All");
        viewAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAllButtonActionPerformed(evt);
            }
        });

        sizeSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S", "M", "L" }));
        sizeSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeSelectActionPerformed(evt);
            }
        });

        enterNum.setForeground(new java.awt.Color(255, 0, 0));
        enterNum.setText("*Just Enter Number");

        enterNum1.setForeground(new java.awt.Color(255, 0, 0));
        enterNum1.setText("*Just Enter Number");

        javax.swing.GroupLayout StudentLayout = new javax.swing.GroupLayout(Student);
        Student.setLayout(StudentLayout);
        StudentLayout.setHorizontalGroup(
            StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentLayout.createSequentialGroup()
                        .addComponent(nameLabel)
                        .addGap(88, 88, 88)
                        .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(StudentLayout.createSequentialGroup()
                        .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(amountLabel)
                                .addComponent(priceLabel, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(sizeLabel1))
                        .addGap(76, 76, 76)
                        .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sizeSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(StudentLayout.createSequentialGroup()
                                .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, StudentLayout.createSequentialGroup()
                                        .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(sellButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(33, 33, 33)
                                        .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(editButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(deleteButton))
                                        .addGap(44, 44, 44)
                                        .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(FindButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(viewAllButton))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(amountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(enterNum)
                                    .addComponent(enterNum1))))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        StudentLayout.setVerticalGroup(
            StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLabel)
                    .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterNum))
                .addGap(14, 14, 14)
                .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountLabel)
                    .addComponent(enterNum1))
                .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(StudentLayout.createSequentialGroup()
                        .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(StudentLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(sizeLabel1))
                            .addGroup(StudentLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(sizeSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addComponent(addButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sellButton))
                    .addGroup(StudentLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, StudentLayout.createSequentialGroup()
                                    .addComponent(editButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(deleteButton))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, StudentLayout.createSequentialGroup()
                                    .addComponent(FindButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(viewAllButton)))
                            .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        displayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Size", "Amount", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        displayTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(displayTable);

        logoLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nghia\\Downloads\\LV.jpg")); // NOI18N

        logo2Label.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nghia\\Downloads\\LV2.jpg")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(logoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(Student, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logo2Label)
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Student, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(logo2Label)))
                .addContainerGap(783, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void priceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTextFieldActionPerformed

    private void amountTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountTextFieldActionPerformed

    private void sellButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellButtonActionPerformed
       int select = displayTable.getSelectedRow();
       SellDialog.setSize(520, 300);
       if(select>=0){
        SellDialog.setVisible(true);
        displayTable.setEnabled(false);
       }
    }//GEN-LAST:event_sellButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        int select = displayTable.getSelectedRow();
       deleteDialog.setSize(380, 200);
       if(select>=0){
        deleteDialog.setVisible(true);
        displayTable.setEnabled(false);
       }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addButtonActionPerformed

    private void addButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonMouseClicked
        // TODO add your handling code here:        
            JTextField nameText = nameTextField;
            JComboBox selectSize = sizeSelect;;
            JTextField priceText = priceTextField;
            JTextField amountText = amountTextField;
            DefaultTableModel dtm = (DefaultTableModel) displayTable.getModel();
            NumberFormat nf = NumberFormat.getInstance(new Locale("en", "US"));
            Regex regex = new Regex();
            
            if((!regex.string(nameText.getText())) || (!regex.number1(priceText.getText())) || (!regex.number1(amountText.getText()))){
                JOptionPane.showMessageDialog(null, "Please re-enter your information");
            } else{
            for (Clothes obj : list) {
            if ((obj.getName().equals(nameText.getText())) && obj.getSize().equals((String)selectSize.getSelectedItem())) {
                if (obj.getPrice() != Integer.parseInt(priceText.getText())) {
                    JOptionPane.showMessageDialog(null, "The product already in the system, please re-enter the price");
                    return;
                } else {
                    int sumAmount = obj.getAmount() + Integer.parseInt(amountText.getText());
                    JOptionPane.showMessageDialog(null, "The product already in the system, increasing amount");
                    obj.setAmount(sumAmount);                                    
//                       truyền thay đổi vào bảng table
                    for (int i = 0; i < dtm.getRowCount(); i++) {
                        if ((dtm.getValueAt(i, 1).equals(nameText.getText())) && (dtm.getValueAt(i, 2).equals((String)selectSize.getSelectedItem()))) {
                            list.get(i).setAmount(sumAmount);
                            dtm.setValueAt(sumAmount, i, 3);
                        }
                    }
                    return;
                }                
            }
        }
            
        Clothes clothes = new Clothes(nameText.getText(), (String)selectSize.getSelectedItem(), Integer.parseInt(amountText.getText()), Integer.parseInt(priceText.getText()));
        list.add(clothes);
        dtm.addRow(new Object[]{clothes.getId(), nameText.getText(), (String)selectSize.getSelectedItem(), Integer.parseInt(amountText.getText()), nf.format(Integer.parseInt(priceText.getText()))});           
            }
    }//GEN-LAST:event_addButtonMouseClicked

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
//        FileOutputStream file = null;
//        ObjectOutputStream object = null;
    try {
        
        FileOutputStream file = new FileOutputStream("clothes.dat");
        ObjectOutputStream object = new ObjectOutputStream(file);

            object.writeObject(list);
        object.close();
    } catch (Exception exception) {
        exception.printStackTrace();
    }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void SellAmountTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SellAmountTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SellAmountTextFieldActionPerformed

    private void SellAmountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SellAmountButtonActionPerformed
        // TODO add your handling code here:
        int indexSelect = displayTable.getSelectedRow();
        DefaultTableModel dtm = (DefaultTableModel) displayTable.getModel();
        JTextField sellAmount = SellAmountTextField;
        if(Integer.parseInt(sellAmount.getText()) >  (Integer) dtm.getValueAt(indexSelect, 3)){
            JOptionPane.showMessageDialog(null, "Out of range");
        } else {
            int subAmount = (Integer) dtm.getValueAt(indexSelect, 3) - Integer.parseInt(sellAmount.getText());
            list.get(indexSelect).setAmount(subAmount);
            dtm.setValueAt(subAmount, indexSelect, 3);
        }
        JOptionPane.showMessageDialog(null, "Successfully");
        
        SellDialog.setVisible(false);
        displayTable.setEnabled(true);
    }//GEN-LAST:event_SellAmountButtonActionPerformed

    private void findByNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findByNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_findByNameTextActionPerformed

    private void findBySizeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findBySizeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_findBySizeTextFieldActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
       int select = displayTable.getSelectedRow();
       JTextField editName = editNameText;
       JComboBox editSelectSize = editSizeSelect;;
       JTextField editPrice = editPriceText;
       JTextField editAmount = editAmountText;
       DefaultTableModel dtm = (DefaultTableModel) displayTable.getModel();
       NumberFormat nf = NumberFormat.getInstance(new Locale("en", "US"));
       editDialog.setSize(520, 300);
       if(select>=0){
        editDialog.setVisible(true);
        displayTable.setEnabled(false);
       }
       editName.setText(list.get(select).getName());
       editSelectSize.setSelectedItem(list.get(select).getSize());
       editAmount.setText(String.valueOf(list.get(select).getAmount()));
       editPrice.setText(String.valueOf(list.get(select).getPrice()));       
    }//GEN-LAST:event_editButtonActionPerformed

    private void FindButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindButtonActionPerformed
        // TODO add your handling code here:
        findDialog.setSize(500, 300);
        findDialog.setVisible(true);
        displayTable.setEnabled(false);
    }//GEN-LAST:event_FindButtonActionPerformed

    private void findByNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findByNameButtonActionPerformed
        // TODO add your handling code here:
        JTextField findByNameText = this.findByNameText;       
        List <Clothes> findByNameList = new ArrayList<>();
        DefaultTableModel dtm = (DefaultTableModel) displayTable.getModel();
        dtm.setRowCount(0);
        NumberFormat nf = NumberFormat.getInstance(new Locale("en", "US"));
        
        for (int i =0; i<list.size(); i++) {
            if(list.get(i).getName().contains(findByNameText.getText())){
            findByNameList.add(list.get(i));
           }  
        }
        for(Clothes clothes: findByNameList){
            dtm.addRow(new Object[]{clothes.getId(), clothes.getName(), clothes.getSize(), clothes.getAmount(), nf.format(clothes.getPrice())});
        }
        findDialog.setVisible(false);
        displayTable.setEnabled(true);
        findByNameText.setText(null);                                        
    }//GEN-LAST:event_findByNameButtonActionPerformed

    private void findBySizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findBySizeButtonActionPerformed
        // TODO add your handling code here:
        JTextField findBySizeText = this.findBySizeTextField;       
        List <Clothes> findBySizeList = new ArrayList<>();
        DefaultTableModel dtm = (DefaultTableModel) displayTable.getModel();
        NumberFormat nf = NumberFormat.getInstance(new Locale("en", "US"));
        dtm.setRowCount(0);   
        
        for (int i =0; i<list.size(); i++) {
            if((findBySizeText.getText()).equals(list.get(i).getSize())){
            findBySizeList.add(list.get(i));
           }  
        }
        for(Clothes clothes: findBySizeList){
            dtm.addRow(new Object[]{clothes.getId(), clothes.getName(), clothes.getSize(), clothes.getAmount(), nf.format(clothes.getPrice())});
        }
        findDialog.setVisible(false);
        displayTable.setEnabled(true);
        findBySizeText.setText(null);
    }//GEN-LAST:event_findBySizeButtonActionPerformed

    private void viewAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAllButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) displayTable.getModel();
        NumberFormat nf = NumberFormat.getInstance(new Locale("en", "US"));
        dtm.setRowCount(0);
        for(Clothes clothes: list){
            dtm.addRow(new Object[]{clothes.getId(), clothes.getName(), clothes.getSize(), clothes.getAmount(), nf.format(clothes.getPrice())});
        }
    }//GEN-LAST:event_viewAllButtonActionPerformed

    private void sizeSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeSelectActionPerformed
        // TODO add your handling code here:           
    }//GEN-LAST:event_sizeSelectActionPerformed

    private void findMinTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findMinTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_findMinTextActionPerformed

    private void findMaxTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findMaxTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_findMaxTextActionPerformed

    private void findByPriceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findByPriceButtonActionPerformed
        // TODO add your handling code here:
        JTextField findMinText = this.findMinText; 
        JTextField findMaxText = this.findMaxText;
        List <Clothes> findByPriceList = new ArrayList<>();
        DefaultTableModel dtm = (DefaultTableModel) displayTable.getModel();
        NumberFormat nf = NumberFormat.getInstance(new Locale("en", "US"));
        dtm.setRowCount(0);   
        
        for (int i =0; i<list.size(); i++) {
            if((Integer.parseInt(findMinText.getText())*1000)<(list.get(i).getPrice()) && ((list.get(i).getPrice()) < (Integer.parseInt(findMaxText.getText()))*1000)){
            findByPriceList.add(list.get(i));
           }  
        }
        for(Clothes clothes: findByPriceList){
            dtm.addRow(new Object[]{clothes.getId(), clothes.getName(), clothes.getSize(), clothes.getAmount(), nf.format(clothes.getPrice())});
        }
        findDialog.setVisible(false);
        displayTable.setEnabled(true);
        findMinText.setText(null);
        findMaxText.setText(null);
    }//GEN-LAST:event_findByPriceButtonActionPerformed

    private void priceTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceTextFieldKeyPressed
        // TODO add your handling code here:
        JTextField priceText = priceTextField;
        JLabel num = enterNum;
        try{
        Regex regex = new Regex();
        if(!regex.number((priceText.getText()))){
            num.setVisible(true);
        } else if(regex.number((priceText.getText()))){
            num.setVisible(false);
        }
        } catch (Exception ex){
            ex.getStackTrace();
        }
    }//GEN-LAST:event_priceTextFieldKeyPressed

    private void editSizeSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSizeSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editSizeSelectActionPerformed

    private void editAmountTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAmountTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editAmountTextActionPerformed

    private void editPriceTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPriceTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editPriceTextActionPerformed

    private void editPriceTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editPriceTextKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_editPriceTextKeyPressed

    private void editNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editNameTextActionPerformed

    private void okEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okEditButtonActionPerformed
        // TODO add your handling code here:
        JTextField editName = editNameText;
        JComboBox editSelectSize = editSizeSelect;;
        JTextField editPrice = editPriceText;
        JTextField editAmount = editAmountText;
        DefaultTableModel dtm = (DefaultTableModel) displayTable.getModel();
        NumberFormat nf = NumberFormat.getInstance(new Locale("en", "US"));
        Regex regex = new Regex();
        int select = displayTable.getSelectedRow();
        
        Clothes editClothes = list.get(select);
        editClothes.setName(editName.getText());
        editClothes.setSize((String)editSelectSize.getSelectedItem());
        editClothes.setAmount(Integer.parseInt(editAmount.getText()));
        editClothes.setPrice(Integer.parseInt(editPrice.getText()));
        
        dtm.setValueAt(editClothes.getName(), select, 1);
        dtm.setValueAt(editClothes.getSize(), select, 2);
        dtm.setValueAt(editClothes.getAmount(), select, 3);
        dtm.setValueAt((nf.format(editClothes.getPrice())), select, 4);
        
        
        editDialog.setVisible(false);
        displayTable.setEnabled(true);
    }//GEN-LAST:event_okEditButtonActionPerformed

    private void amountTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountTextFieldKeyPressed
        // TODO add your handling code here:
        JTextField amountText = amountTextField;
        JLabel num1 = enterNum1;
        try{
        Regex regex = new Regex();
        if(!regex.number((amountText.getText()))){
            num1.setVisible(true);
        } else if(regex.number((amountText.getText()))){
            num1.setVisible(false);
        }
        } catch (Exception ex){
            ex.getStackTrace();
        }
    }//GEN-LAST:event_amountTextFieldKeyPressed

    private void FindButtonMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FindButtonMouseDragged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_FindButtonMouseDragged

    private void YesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YesActionPerformed
        // TODO add your handling code here:
        int select = displayTable.getSelectedRow();
        DefaultTableModel dtm = (DefaultTableModel) displayTable.getModel();
        
        list.remove(list.get(select));
        dtm.removeRow(select);
        
        deleteDialog.setVisible(false);
        displayTable.setEnabled(true);
    }//GEN-LAST:event_YesActionPerformed

    private void NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoActionPerformed
        // TODO add your handling code here:
        deleteDialog.setVisible(false);
        displayTable.setEnabled(true);
    }//GEN-LAST:event_NoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FindButton;
    private javax.swing.JButton No;
    private javax.swing.JButton SellAmountButton;
    private javax.swing.JTextField SellAmountTextField;
    private javax.swing.JDialog SellDialog;
    private javax.swing.JPanel Student;
    private javax.swing.JButton Yes;
    private javax.swing.JButton addButton;
    private javax.swing.JLabel amountLabel;
    private javax.swing.JLabel amountLabel1;
    private javax.swing.JTextField amountTextField;
    private javax.swing.JButton deleteButton;
    private javax.swing.JDialog deleteDialog;
    private javax.swing.JTable displayTable;
    private javax.swing.JTextField editAmountText;
    private javax.swing.JButton editButton;
    private javax.swing.JDialog editDialog;
    private javax.swing.JTextField editNameText;
    private javax.swing.JTextField editPriceText;
    private javax.swing.JComboBox<String> editSizeSelect;
    private javax.swing.JLabel enterNum;
    private javax.swing.JLabel enterNum1;
    private javax.swing.JLabel findByName;
    private javax.swing.JButton findByNameButton;
    private javax.swing.JTextField findByNameText;
    private javax.swing.JLabel findByPrice;
    private javax.swing.JLabel findByPrice1;
    private javax.swing.JLabel findByPrice2;
    private javax.swing.JButton findByPriceButton;
    private javax.swing.JLabel findBySize;
    private javax.swing.JButton findBySizeButton;
    private javax.swing.JTextField findBySizeTextField;
    private javax.swing.JDialog findDialog;
    private javax.swing.JTextField findMaxText;
    private javax.swing.JTextField findMinText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo2Label;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameLabel1;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton okEditButton;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel priceLabel1;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel sellAmountLabel;
    private javax.swing.JButton sellButton;
    private javax.swing.JLabel sizeLabel1;
    private javax.swing.JLabel sizeLabel2;
    private javax.swing.JComboBox<String> sizeSelect;
    private javax.swing.JButton viewAllButton;
    // End of variables declaration//GEN-END:variables

    private boolean regex(String text) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
